<!DOCTYPE html>
<html>
<head>
    <title>{{ $title }}</title>

    <style>
        /* ===============================
           Global PDF Page Styling
        ================================ */
        body {
            font-family: DejaVu Sans, sans-serif; /* Supports all Unicode text */
            margin: 50px;                         /* Clean page margin */
        }

        /* ===============================
           Header Title Styling
        ================================ */
        h1 {
            font-size: 32px;
            font-weight: bold;
            margin-bottom: 20px;
        }

        /* ===============================
           Date Styling
        ================================ */
        .date {
            font-size: 14px;
            margin-bottom: 25px;
        }

        /* ===============================
           Paragraph Styling
        ================================ */
        p {
            font-size: 14px;
            line-height: 22px;        /* Better readability */
            text-align: justify;       /* Makes paragraph look professional */
        }

        /* ===============================
           Dynamic Table Styling
        ================================ */
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 35px;
        }

        th, td {
            border: 1px solid #333;
            padding: 10px;
            font-size: 14px;
        }

        th {
            background: #f0f0f0;        /* Light grey header for clean look */
        }
    </style>
</head>

<body>

    <!--  COMPANY HEADER -->
    <div style="text-align:center;">
        <h2 style="margin-bottom:5px;">User Report</h2>
        <small>Generated by Laravel PDF System</small>
    </div>

    <hr>

    <!-- Title -->
    <h1>{{ $title }}</h1>

    <!-- Date -->
    <div class="date">
        Date: {{ $date }}
    </div>

    <!-- Total Users -->
    <p><strong>Total Users:</strong> {{ $total }}</p>

    <!-- Description -->
    <p>
        This report contains dynamically generated user data. It showcases how Laravel
        can generate structured and professional PDF documents using Blade templates.
    </p>

    <!--  TABLE -->
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Created At</th>
            </tr>
        </thead>
        <tbody>
            @forelse($users as $user)
                <tr>
                    <td>{{ $user->id }}</td>
                    <td>{{ $user->name }}</td>
                    <td>{{ $user->email }}</td>
                    <td>{{ $user->created_at->format('d-m-Y') }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="4">No users found</td>
                </tr>
            @endforelse
        </tbody>
    </table>

</body>
</html>
